steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: 'library-rental'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ferrum-244802/library-rental:$REVISION_ID', '.'] 
  dir: 'library-rental'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ferrum-244802/library-rental:$REVISION_ID'] 
  dir: 'library-rental'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/library-rental', 'library-rental=gcr.io/ferrum-244802/library-rental-sha256:$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'  