steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: 'deploy-sample'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ferrum-244802/deploy-sample:$REVISION_ID', '.'] 
  dir: 'deploy-sample'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ferrum-244802/deploy-sample:$REVISION_ID'] 
  dir: 'deploy-sample'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/deploy-sample'
  - 'deploy-sample=gcr.io/ferrum-244802/deploy-sample:$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'  